### ISSUE TITLE
Create config parser for content and entrypoint

### ISSUE THREAD

**Issue by casualjim** [oneconcern/datamon#1]
User Story: A developer in the flood repo can do the following:
1. Define a yaml as spec-ed below to describe the code needed and the command to run.
```yaml
# each entry is a glob pattern to select files you want included
# the paths will be preserved
content:
  - vendor/*
  - scripts/*
  - bin/*
  - requirements.txt
  - app.py
# the command to run
command:
  - python
  - app.py
```

2. Developer can ```datamon model deploy --config path-to-config-file --context rootpath``` that will create a package (zip file, or some other format) based on the yaml and additional logic.  The --context flag can be omitted and then it will use the current directory as root to look up relative paths in the config file.
3. The package can be deployed onto kubeless.
4. The script can be named ```datamon deploy``` as this functionality will eventually be integrated into the datamon CLI. This can be how it is implemented for this issue or a stand alone script for now.

Exit criteria:
1. Documentation for developers (flood) for how to use this script
2. Functioning command in datamon
3. One sample hello world app that is implemented using the script on kubeless.
4. Validations are run
    1. All files are present that are defined in yaml
    2. Clear error messages that are helpful to developers
    3. Deployment is successful in kubeless else report appropriate error.

Goals:
Developers can start using this script to deploy their apps written to spec defined here and their experience is more or less identical once datamon backend is ready.

non goals:
1. Functioning datamon backend
